name: Nuget

on:
  create:
    tags:
      - v*

jobs:
  release:

    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2

    - uses: microsoft/setup-msbuild@v1

    - uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build the application
      run: msbuild /p:Configuration=Release

    - name: Depoly to Nuget
      run: Get-ChildItem -Recurse -Filter *.nupkg | Foreach-Object {Invoke-Command nuget push setapikey $nuget_api_key $_.FullName}
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
